=== Garlisio/Chog/rocks.dtd
<!ELEMENT rocks (rock)>
<!ELEMENT rock (name,type,value,quantity,weight,height,width,observations)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT observations (#PCDATA)>
<!ATTLIST weight system ID #IMPLIED>
<!ATTLIST height system ID #IMPLIED>
<!ATTLIST width system ID #IMPLIED>
<!ATTLIST value currency ID #IMPLIED>

<!-- Rock Archives-->

=== Garlisio/Chog/rocks.xml
<!DOCTYPE rocks PUBLIC "SYSTEM" "rocks.dtd">

<rocks>
    <rock>
        <name>Diamond</name>
        <type>Precious</type>
        <value currency="dollars">50000000</value>
        <quantity>1</quantity>
        <weight system="pounds">11</weight>
        <height system="inches">8</height>
        <width system="feet">2</width>
        <observations>Shiny</observations>
    </rock>
</rocks>
